extends Node

signal score_changed(new_score)
signal health_changed(new_health)
signal level_changed(new_level_name)

var score: int = 0
var health: int = 3
var current_level_path: String = "res://scenes/Main.tscn"
var current_level_name: String = "1"

var last_life_score: int = 0

# Stats for Victory Screen
var stats_health_gained: int = 0
var stats_health_lost: int = 0
var stats_double_jumps: int = 0
var stats_total_playtime: float = 0.0
var stats_level_completion_times: Array[float] = []

var _level_start_time: float = 0.0

var sfx_kill: AudioStreamPlayer
var sfx_damage: AudioStreamPlayer
var sfx_life: AudioStreamPlayer

func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS # Ensure global state works even when paused, though audio usually does.
	
	sfx_kill = AudioStreamPlayer.new()
	sfx_kill.stream = load_wav("res://assets/audio/kill.wav")
	add_child(sfx_kill)
	
	sfx_damage = AudioStreamPlayer.new()
	sfx_damage.stream = load_wav("res://assets/audio/damage.wav")
	add_child(sfx_damage)
	
	sfx_life = AudioStreamPlayer.new()
	sfx_life.stream = load_wav("res://assets/audio/life.wav")
	add_child(sfx_life)

func load_wav(path: String) -> AudioStream:
	var stream = load(path)
	if not stream and FileAccess.file_exists(path):
		# Fallback for missing .import files
		var file = FileAccess.open(path, FileAccess.READ)
		if file:
			var bytes = file.get_buffer(file.get_length())
			var wav = AudioStreamWAV.new()
			# Assumes mono 44.1k 16bit WAV (generated by our scripts)
			wav.data = bytes.slice(44) 
			wav.format = AudioStreamWAV.FORMAT_16_BITS
			wav.mix_rate = 44100
			stream = wav
	return stream

func reset():
	score = 0
	health = 3
	last_life_score = 0
	stats_health_gained = 0
	stats_health_lost = 0
	stats_double_jumps = 0
	stats_total_playtime = 0.0
	stats_level_completion_times = []
	_level_start_time = Time.get_ticks_msec() / 1000.0
	score_changed.emit(score)
	health_changed.emit(health)

func start_level_timer():
	_level_start_time = Time.get_ticks_msec() / 1000.0

func complete_level():
	var end_time = Time.get_ticks_msec() / 1000.0
	var duration = end_time - _level_start_time
	stats_level_completion_times.append(duration)
	stats_total_playtime += duration

func add_score(amount: int):
	score += amount
	score_changed.emit(score)
	
	# Check for extra life every 100 points
	if score >= last_life_score + 100:
		health += 1
		stats_health_gained += 1
		last_life_score += 100
		health_changed.emit(health)
		sfx_life.play()

func play_kill_sound():
	sfx_kill.play()

func record_double_jump():
	stats_double_jumps += 1

func take_damage(amount: int):
	health -= amount
	stats_health_lost += amount
	health_changed.emit(health)
	sfx_damage.play()
	if health <= 0:
		game_over()

func respawn():
	health -= 1
	stats_health_lost += 1
	health_changed.emit(health)
	sfx_damage.play()
	if health <= 0:
		game_over()
	else:
		get_tree().reload_current_scene()

func game_over():
	get_tree().change_scene_to_file("res://scenes/ui/GameOver.tscn")

func restart_game():
	reset()
	get_tree().reload_current_scene()
